# env:
#   TERM: xterm-256color

# window:
#   dimensions:
#     columns: 100
#     lines: 60
#   dynamic_padding: true
#   decorations: full
#   title: Alacritty@Garuda
#   opacity: 1
#   class:
#     instance: Alacritty
#     general: Alacritty
#   gtk_theme_variant: dark
#   padding:
#     x: 20
#     y: 20


# scrolling:
#   history: 10000
#   multiplier: 3

# font:
#   size: 14
#   normal:
#     family: Iosevka
#   bold:
#     style: Bold  
#     family: Iosevka
#   italic:
#     family:  Iosevka
#   bold_italic:
#     family:  Iosevka
#     style: Bold
#     size: 13

# draw_bold_text_with_bright_colors: true

# save_to_clipboard: true

# window.dynamic_title: true

# cursor:
#   style: Underline

# live_config_reload: true

# shell:
#   program: /usr/bin/zsh
#   args:
#     - --login

# mouse:
#   hide_when_typing: true

# key_bindings:
#     # (Windows, Linux, and BSD only)
#   - { key: V,        mods: Control|Shift, action: Paste            }
#   - { key: C,        mods: Control|Shift, action: Copy             }
#   - { key: Insert,   mods: Shift,         action: PasteSelection   }
#   - { key: Key0,     mods: Control,       action: ResetFontSize    }
#   - { key: Equals,   mods: Control,       action: IncreaseFontSize }
#   - { key: Plus,     mods: Control,       action: IncreaseFontSize }
#   - { key: Minus,    mods: Control,       action: DecreaseFontSize }
#   - { key: Minus,    mods: Control,       action: DecreaseFontSize }

# # Colors (Pencil Light)
# colors:
#   # Default Colors
#   primary:
#     background: '0xf1f1f1'
#     foreground: '0x424242'
#   # Normal colors
#   normal:
#     black:   '0x212121'
#     red:     '0xc30771'
#     green:   '0x10a778'
#     yellow:  '0xa89c14'
#     blue:    '0x008ec4'
#     magenta: '0x523c79'
#     cyan:    '0x20a5ba'
#     white:   '0xe0e0e0'
#   # Bright colors
#   bright:
#     black:   '0x212121'
#     red:     '0xfb007a'
#     green:   '0x5fd7af'
#     yellow:  '0xf3e430'
#     blue:    '0x20bbfc'
#     magenta: '0x6855de'
#     cyan:    '0x4fb8cc'
#     white:   '0xf1f1f1'

# # Colors (Gruvbox Material Dark Medium)
# colors:
#   primary:
#     background: '0x282828'
#     foreground: '0xdfbf8e'

#   normal:
#     black:   '0x665c54'
#     red:     '0xea6962'
#     green:   '0xa9b665'
#     yellow:  '0xe78a4e'
#     blue:    '0x7daea3'
#     magenta: '0xd3869b'
#     cyan:    '0x89b482'
#     white:   '0xdfbf8e'

#   bright:
#     black:   '0x928374'
#     red:     '0xea6962'
#     green:   '0xa9b665'
#     yellow:  '0xe3a84e'
#     blue:    '0x7daea3'
#     magenta: '0xd3869b'
#     cyan:    '0x89b482'
#     white:   '0xdfbf8e'

# Colors (Gruvbox dark)
colors:
  primary:
    # hard contrast background - '#1d2021'
    background:        &gruvbox_dark_bg '#282828'
    # soft contrast background - '#32302f'
    foreground:        '#ebdbb2'
    bright_foreground: '#fbf1c7'
    dim_foreground:    '#a89984'
  cursor:
    text:   CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text:   CellBackground
    cursor: CellForeground
  # search:
  #   matches:
  #     foreground: '#000000'
  #     background: '#ffffff'
  #   focused_match:
  #    foreground: CellBackground
  #    background: CellForeground
  #   bar:
  #     background: ''
  #     foreground: ''
  # line_indicator:
  #   foreground: None
  #   background: None
  selection:
    text:       CellBackground
    background: CellForeground
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
  normal:
    black:   *gruvbox_dark_bg
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  dim:
    black:   '#32302f'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#928374'
  indexed_colors:
    - { index:  66, color: '#458588' }
    - { index:  72, color: '#689d6a' }
    - { index: 106, color: '#98971a' }
    - { index: 108, color: '#8ec07c' }
    - { index: 109, color: '#83a598' }
    - { index: 124, color: '#cc241d' }
    - { index: 132, color: '#b16286' }
    - { index: 142, color: '#b8bb26' }
    - { index: 166, color: '#d65d0e' }
    - { index: 167, color: '#fb4934' }
    - { index: 172, color: '#d79921' }
    - { index: 175, color: '#d3869b' }
    - { index: 208, color: '#fe8019' }
    - { index: 214, color: '#fabd2f' }
    - { index: 223, color: '#ebdbb2' }
    - { index: 229, color: '#fbf1c7' }
    - { index: 234, color: '#1d2021' }
    - { index: 235, color: '#282828' }
    - { index: 236, color: '#32302f' }
    - { index: 237, color: '#3c3836' }
    - { index: 239, color: '#504945' }
    - { index: 241, color: '#665c54' }
    - { index: 243, color: '#7c6f64' }
    - { index: 245, color: '#928374' }
    - { index: 246, color: '#a89984' }
    - { index: 248, color: '#bdae93' }
    - { index: 250, color: '#d5c4a1' }